global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'my-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.1.191:5002']
